test:
  host: tags-service-development.herokuapp.com
  port: 80
  api_version: 1

development:
  host: tags-service-development.herokuapp.com
  port: 80
  api_version: 1
  max_concurrency: 4

production:
  host: tags-service.herokuapp.com
  port: 80
  api_version: 1
  max_concurrency: 10
